[package]
name = "coffee-break"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.8"
duration-string = "0.4.0"
fork = "0.1.23"
sysinfo = "0.30.12"
